<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" />
    <PackageReference Include="PdfPig" />
    <PackageReference Include="PDFtoImage" />
    <PackageReference Include="System.Drawing.Common" />
  </ItemGroup>
</Project>
