<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Hormiguero.Diseno\Hormiguero.Diseno.csproj" />
    <ProjectReference Include="..\Hormiguero.Buscadero.Logica\Hormiguero.Buscadero.Logica.csproj" />
  </ItemGroup>
</Project>
